### ISSUE TITLE
Code treaties for membership design

### ISSUE THREAD

**Issue by jhollway** [globalgov/manyenviron#44]

**Comment by EstherPeev** [comment]
Before coding treaties in manyenviron databases and categorizing them according to their memberships design, I wanted to share a proposal of the categories we could used. 

Please, find below an example of a categorization schema we could follow:

[https://app.zenhub.com/files/326714201/390dbaef-20cd-4355-9988-3152045f0e46/download](https://app.zenhub.com/files/326714201/390dbaef-20cd-4355-9988-3152045f0e46/download)

It is a quite simple one, but please let me know if you were thinking of a more precise way of differentiating treaties based one their membership design @jhollway
