### ISSUE TITLE
Issue with connecting vignette in manyenviron

### ISSUE THREAD

**Issue by henriquesposito** [globalgov/manyenviron#48]
It appears that igraph::bipartite.projection() used by migraph::project_cols() (line 223) is not currently running. The issue is new, as vignette was building properly yesterday... 

For now I set the code chunk to not run (eval=false), but could you please take a look at this?

**Comment by BBieri** [comment]
Thanks for reporting! I was able to reproduce the error and I'll have a look to fix it as soon as I can.

**Comment by BBieri** [comment]
It is fixed! Basically, the `lvl` node attribute we need for the 3D bipartite projection graph was throwing `{igraph}` off when doing the unimodal projection for the globe graph.
