### ISSUE TITLE
Integrate shiny dashboard plots into the dashboard vignette

### ISSUE THREAD

**Issue by EstherPeev** [globalgov/manyenviron#53]
A Shinyapp folder has been created with three different folders (two on lineage and one on memberships). Each of the app file that is contained in the folder should connect to a Shinyapp account using GitHub. I didn't succeed connect it to my Shinyapp account, but should be certainly possible through a new Shinyapp account linked to the globalgov GitHub page?

Then, a dashboard vignette has been added with a url from the Shinyapp. The url provided in the vignette (https://globalgov.shinyapps.io/lineage/) is linked to my account and represent graphs developed in another package than `{manyenviron}`. This should be changed once the app files in `{manyenviron}` are connected to another Shinyapp account using the functions from `{rsconnect}` package. 

Finally,  I have created the same folders in `{manytrade}` so the same process as described above should be repeated there.

**Comment by henriquesposito** [comment]
The shiny apps and vignettes in manyenviron and on manytrade developed have been all updated and connected to my shiny.io account for now. They have been deployed as well, see the links below.

https://genevaglobalgov.shinyapps.io/lineage/
https://genevaglobalgov.shinyapps.io/memberships/
https://genevaglobalgov.shinyapps.io/trade_treaties_year/

They still need to be improved and deployed within websites or their respective GitHub pages, I will open a new issue for this now.
