### ISSUE TITLE
Make sure variables are in standard unambiguous format for `consolidate()` to run properly

### ISSUE THREAD

**Issue by henriquesposito** [globalgov/manyenviron#55]
This is a similar issue to the one we have with manystates, however, in this case a bit trickier since manyenviron had a recent release and consolidate() does not run on some of the databases there. I would suggest we address these issues before we merge the PR in manydata and release on CRAN so that users can indeed use `consolidate()`in manyenviron.

The `consolidate()` function assumes that variables with the same name across datasets in the same database should be in the same class/format, otherwise it trows an error. However, it identify variables by a common prefix to resolve them. For example, in the agreements database in the main branch of manyenviron we have different variable that start with the same prefix "L" (i.e. L and Lineage) and that are different. So once all the variables that begin with "L" are resolved `consolidate()`does not find any more "Lineage" variables to be resolved. Therefore we need to rename these so that they have different prefixes in their name if we are to keep both variables in the dataset/database.

@jaeltan could you please take a look at these variable level issues of consistency and make sure they are solved across the databases and open a new PR for manyagreements? 

Please also double check if we have some of the same issues in the manyhealth and manytrade packages as well. If so, please open issues for these. Thank you!

**Comment by jaeltan** [comment]
I've renamed the 'Lineage' column in the agreements database to 'R' for now so that the names of the variables don't clash and `consolidate()` works.
