### ISSUE TITLE
Standardise variables across datasets

### ISSUE THREAD

**Issue by henriquesposito** [globalgov/manyenviron#70]
Some variables from IEADB and ECOLEX were left out these datasets when they were added to the agreements database. Check which variables we want to add back.

**Comment by jaeltan** [comment]
**List of omitted variables in datasets**
CIESIN: omitted signatories, parties, total, and former parties
ECOLEX: omitted Spanish title, French title, place of adoption, depository, language, subject, keyword, geographical area, abstract, Full text, website, legislation, literature, other title, online course, treaty decisions, Basin, Title abbreviated, Comment, Link to abstract, jurisprudence
HEIDI: omitted Signatories, Preamble refers to health, Importance of a resource for human health, etc (variables on articles that relate to health governance)
IEADB: omitted Treaty Text, Members, Lineage (this variable is replaced by one that we code using `manypkgs::code_lineage()`, Sequence in lineage, Data, Articles, Secretariat, UNEP info

**Comment by jhollway** [comment]
This issue has gone stale. What's the next step(s) here?

**Comment by jaeltan** [comment]
@jhollway @henriquesposito I'm going to close this issue since none of the omitted variables contain useful information for HUGGO datasets. I think we can leave this for now, and come back to it if some of the information is useful as reference for AIGGO later on.
